name: bookmap
description: bookmap project by fentarim

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.19.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  http: ^0.13.3
  firebase_auth: ^4.1.2
  firebase_core: ^2.2.0
  flutterfire_ui: ^0.4.3+20

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_native_splash: ^2.2.19

flutter_native_splash:
  color: "#ffffff" #white
  image: assets/splash.png

flutter:
  uses-material-design: true
  assets:
    - images/logo.png