name: bookmap
description: bookmap project by fentarim

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.19.1 <3.0.0'

dependencies:
  flutter_web_auth: ^0.5.0
  table_calendar: ^3.0.9
  flutter:
    sdk: flutter
  cached_network_image: ^3.0.0
  percent_indicator: ^4.0.1
  intl: ^0.18.0
  carousel_slider: ^4.2.1
  url_launcher: ^6.1.11
  cupertino_icons: ^1.0.2
  http: ^0.13.4
  firebase_auth: ^4.1.2
  firebase_core: ^2.2.0
  flutterfire_ui: ^0.4.3+20
  cloud_firestore: ^4.8.0
  scroll_date_picker : ^3.7.1
  flutter_rating_stars: ^1.0.3+4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_native_splash: ^2.2.19

flutter_native_splash:
  color: "#ffffff" #white
  image: assets/splash.png
  fullscreen: true

flutter:
  uses-material-design: true
  assets:
    - images/logo.png
    - images/plus_button.png

fading_image_button: ^0.10.0+0
